PS1='\e[32m\u@\h \e[1;36m\w \e[0m\$ '
umask 022
export LS_OPTIONS='--color=auto'
alias c2c2='node /casljs/c2c2.js'
alias pytest='python3 -m pytest'
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias la='ls $LS_OPTIONS -a'
alias l='ls $LS_OPTIONS -lA'
