if [ ! -z "$USE_STARSHIP" ]; then
    eval "$(starship init bash)"
fi

export LS_OPTIONS='--color=auto'
alias c2c2='node /casljs/c2c2.js'
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias la='ls $LS_OPTIONS -a'
alias l='ls $LS_OPTIONS -lA'

source /etc/bash_completion
